### ISSUE TITLE
Documentação do Projeto

### ISSUE THREAD

**Issue by orlandosaraivajr** [DSM-Grupo-06-Projeto-Integrador-2024/dsm-grupo-6-pi#1]
Qual é o tema do software certo a ser feito ?

No dia 24/04, a equipe precisa ter claro qual o software o grupo pretende modelar, e apresentar os primeiros diagramas de **Caso de Uso**.

**Comment by orlandosaraivajr** [comment]
Em anexo, o template para a documentação, apresentado na aula de hoje.

Bom trabalho pessoal !
[Padrão Documentação ES1V1.odt](https://github.com/DSM-Grupo-06-Projeto-Integrador-2024/dsm-grupo-6-pi/files/15255677/Padrao.Documentacao.ES1V1.odt)

**Comment by orlandosaraivajr** [comment]
Em anexo, o template para a documentação, desta vez em formado .docx
Bom trabalho pessoal !
[Projeto Integrador 1º Semestre.docx](https://github.com/DSM-Grupo-06-Projeto-Integrador-2024/dsm-grupo-6-pi/files/15255723/Projeto.Integrador.1.Semestre.docx)

**Comment by julianosantosdev** [comment]
Documentação final já no repositório
